#:include popups/popups.kv

# todo: 1. send contents of new widget to row. when pop opens

# RundownTemplate being used as there will be round 10 screens eventually,
# sharing the same template

ScreenManager:
    id: screen_manager
    LWRundown
        id: lw_rundown
        name: 'lw'
        manager: 'screen_manager'


    DrawingScreen:
        id: drawing_screen
        name: 'drawing'
        manager: 'screen_manager'


<DrawingScreen@MDScreen>
    BoxLayout
        orientation: 'vertical'
        MDIconButton:
            icon: "arrow-left-bold-outline"

            on_press: app.print_status()
            on_release: app.root.current = 'lw'

        Widget

        BoxLayout
            Widget
            MyPaintWidget
                background_color: 0.9, 0.9, 0.9, 1
                size_hint_x: None
                size_hint_y: None
                height: 160
                width: 622.22
            Widget

        Widget


<LWRundown@MDScreen>
    RundownTemplate
        id: lw
        rundown: 'LW'
        data: app.rvdata


<RundownTemplate@MDScreen>
    BoxLayout:
        orientation: 'vertical'
        MDToolbar:
            size_hint_y: None
            height: 90
            title: 'Test'

            MDIconButton:
                icon: "arrow-left-bold-outline"
                on_press: app.root.current = 'drawing'

            MDIconButton:
                icon: "power-on"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

            MDIconButton:
                icon: "arrow-up"

            MDIconButton:
                icon: "arrow-down"

            MDIconButton:
                icon: "format-vertical-align-top"

            MDIconButton:
                icon: "format-vertical-align-bottom"

            MDIconButton:
                icon: "power-on"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

            BoxLayout:
                orientation: 'vertical'
                Widget:
                    size_hint_y: .1
                MDRaisedButton:
                    id: color_button
                    md_bg_color: 0, 0, 0, 1
                    text: 'COLOUR'
                    text_color: 1, 1, 1, 1
                    font_size: 11
                    size_hint_y: .5
                    on_release: app.popups.select_color()
                Widget:
                    size_hint_y: .1
                MDRaisedButton:
                    md_bg_color: 0, 0, 0, 1
                    text: 'THICKNESS'
                    text_color: 1, 1, 1, 1
                    font_size: 11
                    size_hint_y: .5
                    size_hint_x: 1
                    on_release: app.popups.select_width()
                Widget:
                    size_hint_y: .1

            MDIconButton
                id: pencil_button
                icon: "pencil"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
                on_release: app.change_tool('pencil')
                on_release: self.text_color = 1, 1, 1, 1
                on_release: fill_button.text_color = 0, 0, 0, 1
                on_release: eraser_button.text_color = 0, 0, 0, 1
            MDIconButton
                id: fill_button
                icon: "format-color-fill"
                theme_text_color: "Custom"
                on_release: app.change_tool('fill')
                on_release: self.text_color = 1, 1, 1, 1
                on_release: pencil_button.text_color = 0, 0, 0, 1
                on_release: eraser_button.text_color = 0, 0, 0, 1
            MDIconButton
                id: eraser_button
                icon: "eraser"
                theme_text_color: "Custom"
                on_release: self.text_color = 1, 1, 1, 1
                on_release: pencil_button.text_color = 0, 0, 0, 1
                on_release: fill_button.text_color = 0, 0, 0, 1
                on_release: app.change_tool('eraser')
            MDIconButton
                icon: "close-box"
                on_release: app.clear_all_drawings()

        BoxLayout:
            size_hint_y: 0.039
            MDRectangleFlatButton:
                text: '  TIME  '
                text_color: 1, 1, 1, 1
                md_bg_color: 0.098, 0.407, 0.670, 1

            MDRectangleFlatButton:
                text: '                       TITLE                        '
                text_color: 1, 1, 1, 1
                md_bg_color: 0.098, 0.407, 0.670, 1

            MDRectangleFlatButton:
                text: '  CAM  '
                text_color: 1, 1, 1, 1
                md_bg_color: 0.098, 0.407, 0.670, 1

            MDRectangleFlatButton:
                text: '                                  NOTES                                  '
                text_color: 1, 1, 1, 1
                md_bg_color: 0.098, 0.407, 0.670, 1
                on_release: root.status_update()

        # ## ### RECYCLEVIEW ### ## #
        # ## ### RECYCLEVIEW ### ## #
        # ## ### RECYCLEVIEW ### ## #
        RecycleView
            data: app.rvdata
            viewclass: 'Row'
            scroll_type: ['bars']
            bar_width: 40

            RecycleBoxLayout:
                id: rv

                default_size: None, dp(80)
                default_size_hint: 1, None
                size_hint_y: None
                height: self.minimum_height
                orientation: 'vertical'

        MDBoxLayout:
            size_hint_y: .001
            canvas:
                Color:
                    rgb: 0.6, 0.6, 0.6
                Rectangle:
                    pos: self.pos
                    size: self.size

        MDBoxLayout:
            size_hint_y: .02
            canvas:
                Color:
                    rgb: 0.8, 0.8, 0.8
                Rectangle:
                    pos: self.pos
                    size: self.size

            MDLabel:
                id: conn_status
                text: '  STATUS: '
                font_size: 20



